AuthlibInjector:
  Mirrors:
    BMCLAPI: https://bmclapi2.bangbang93.com/mirrors/authlib-injector
    MCBBS: https://download.mcbbs.net/mirrors/authlib-injector
  Official: https://authlib-injector.yushi.moe
Farbic:
  Files:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/maven
      MCBBS: https://download.mcbbs.net/maven
    Official: https://maven.fabricmc.net
  Version:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/fabric-meta
      MCBBS: https://download.mcbbs.net/fabric-meta
    Official: https://meta.fabricmc.net
Forge:
  Version:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/forge/minecraft/:id
      MCBBS: https://download.mcbbs.net/forge/minecraft/:id
    Official: None
Liteloader:
  Mirrors:
    BMCLAPI: https://bmclapi.bangbang93.com/maven/com/mumfrey/liteloader/versions.json
    MCBBS: https://download.mcbbs.net/maven/com/mumfrey/liteloader/versions.json
  Official: http://dl.liteloader.com/versions/versions.json
Minecraft:
  Assets:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/assets
      MCBBS: https://download.mcbbs.net/assets
    Official: http://resources.download.minecraft.net
  Libraries:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/maven/
      MCBBS: https://download.mcbbs.net/maven/
    Official: https://libraries.minecraft.net/
  Self:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com
      MCBBS: https://download.mcbbs.net
    Official: https://launcher.mojang.com
    Path: /version/{version}/{category}
  Versions:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com
      MCBBS: https://download.mcbbs.net
    Official: https://launchermeta.mojang.com
    Path: /mc/game/version_manifest_v2.json
Mojang:
  Java:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json
      MCBBS: https://download.mcbbs.net/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json
    Official: https://launchermeta.mojang.com/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json
Optifine:
  File:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/optifine/:mcversion/:type/:patch
      MCBBS: https://download.mcbbs.net/optifine/:mcversion/:type/:patch
    Official: None
  Versions:
    Mirrors:
      BMCLAPI: https://bmclapi2.bangbang93.com/optifine/:mcversion
      MCBBS: https://download.mcbbs.net/optifine/:mcversion
    Official: None
